### ISSUE TITLE
cargo hakari missing cfg-specific dependencies?

### ISSUE THREAD

**Issue by VorpalBlade** [guppy-rs/guppy#312]
I have this in some of my bin packages in my workspace:

```toml
[target.'cfg(target_env = "musl")'.dependencies]
# The allocator on musl is attrociously slow, so we use a custom one.
# Jemalloc doesn't work reliably on Aarch64 due to varying page size, so use
# the slightly slower mimalloc instead.
mimalloc.workspace = true
```

And in my virtual workspace manifest I have:

```toml
[workspace.dependencies]
# ...
mimalloc = "0.1.43"
# ...
```

For some reason mimalloc doesn't show up in the generated workspace_hack `Cargo.toml`. I have the following in my `hakari.toml`:

```toml
platforms = [
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
    "armv7-unknown-linux-gnueabihf",
    "armv7-unknown-linux-musleabihf",
    "i686-unknown-linux-gnu",
    "i686-unknown-linux-musl",
    "riscv64gc-unknown-linux-gnu",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
]
```

So I really think that mimalloc *should* show up for the musl targets?
